#!/usr/bin/env python3
"""
Read 12 monthly CSVs exported from alemanha-2025.xlsx and emit a single
idempotent SQL seed at scripts/seed-from-xlsx.sql.

The CSVs are a category-by-slot matrix: column A is the category name,
columns B..V are individual transaction amounts (max 21 per row), column W
is the row total. Empty cells are encoded as €0.00 and are skipped.

Wallet and user are hard-coded — re-running the seed wipes only this
wallet's transactions and categories before reinserting.
"""

from __future__ import annotations

import csv
import re
from pathlib import Path

WALLET_ID = "3c27075c-386e-40c4-a679-f81fe7b05536"
USER_ID = "5fb576d6-8827-457c-ad56-f7c6ecde7ead"

INPUT_DIR = Path("/Users/denistoledo/Downloads")
OUTPUT_PATH = Path(__file__).resolve().parent / "seed-from-xlsx.sql"

MONTH_LABELS = [
    ("Janeiro", 1),
    ("Fevereiro", 2),
    ("Março", 3),
    ("Abril", 4),
    ("Maio", 5),
    ("Junho", 6),
    ("Julho", 7),
    ("Agosto", 8),
    ("Setembro", 9),
    ("Outubro", 10),
    ("Novembro", 11),
    ("Dezembro", 12),
]

# (year, last_month_to_import). Months past last_month are skipped for the year.
YEARS = [
    (2025, 12),
    (2026, 5),
]

# Unify drifted names to the latest form. DeskBuddy and Workspacey are kept
# distinct on purpose (per the user's instruction).
NAME_ALIASES = {
    "Apple Store": "Apple",
    "Energia/Luz": "Energia/Luz/Gas",
}

FOOTER_PREFIXES = ("updated at", "last update")


def parse_amount_to_cents(raw: str) -> int | None:
    """Return integer minor units, or None if the cell is empty / zero."""
    s = raw.strip().lstrip("€").strip()
    if not s:
        return None
    # Distinguish English (€1,350.00) from German (27,37) by the presence of '.'.
    if "." in s:
        s = s.replace(",", "")          # comma = thousands separator
    else:
        s = s.replace(",", ".")         # comma = decimal separator
    try:
        value = float(s)
    except ValueError:
        raise ValueError(f"Cannot parse amount: {raw!r}")
    cents = round(value * 100)
    return cents if cents > 0 else None


def canonical_name(raw: str) -> str:
    name = raw.strip()
    return NAME_ALIASES.get(name, name)


def collect():
    # category name -> (year, month) of first appearance in any sheet
    categories: dict[str, tuple[int, int]] = {}
    # (name, cents, year, month, day)
    transactions: list[tuple[str, int, int, int, int]] = []

    for year, last_month in YEARS:
        for label, month in MONTH_LABELS:
            if month > last_month:
                break
            path = INPUT_DIR / f"alemanha-{year}.xlsx - {label}.csv"
            with path.open(encoding="utf-8") as fh:
                reader = csv.reader(fh)
                for row in reader:
                    if not row or not row[0].strip():
                        continue
                    first = row[0].strip()
                    low = first.lower()
                    if first == "0" or any(low.startswith(p) for p in FOOTER_PREFIXES):
                        continue
                    name = canonical_name(first)
                    # Slots are columns 1..21 (index 1 through 21 inclusive).
                    # Column 22 is the row total — skip it.
                    slots = row[1:22]
                    for idx, cell in enumerate(slots, start=1):
                        cents = parse_amount_to_cents(cell)
                        if cents is None:
                            continue
                        transactions.append((name, cents, year, month, idx))
                    # Even rows with all zeros (e.g. Médicos, Fitness) become a
                    # category so the user can use them later. created_at is
                    # set to the first month the row appeared in any sheet.
                    if name not in categories:
                        categories[name] = (year, month)

    return categories, transactions


def sql_string(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


def emit(categories: dict[str, tuple[int, int]], transactions: list[tuple[str, int, int, int, int]]) -> str:
    lines: list[str] = []
    lines.append("-- =====================================================================")
    year_summary = ", ".join(f"{y} (Jan–{MONTH_LABELS[lm-1][0]})" for y, lm in YEARS)
    lines.append(f"-- Seed from alemanha-*.xlsx monthly CSVs: {year_summary}.")
    lines.append("--")
    lines.append(f"-- Wallet:    {WALLET_ID}")
    lines.append(f"-- Created by: {USER_ID}")
    lines.append("--")
    lines.append("-- Idempotent: wipes this wallet's transactions and categories first,")
    lines.append("-- then reinserts. Safe to re-run.")
    lines.append("--")
    lines.append("-- Generated by scripts/build-seed-from-xlsx.py. Do not edit by hand;")
    lines.append("-- re-run the script if the source CSVs change.")
    lines.append("-- =====================================================================")
    lines.append("")
    lines.append("begin;")
    lines.append("")
    lines.append("-- 1. Wipe existing data for this wallet only.")
    lines.append(f"delete from public.transactions where wallet_id = {sql_string(WALLET_ID)};")
    lines.append(f"delete from public.categories   where wallet_id = {sql_string(WALLET_ID)};")
    lines.append("")
    lines.append("-- 2. Recreate categories (all expense). created_at reflects")
    lines.append("--    the first month the category appeared in any sheet.")
    cat_rows = ",\n  ".join(
        f"({sql_string(WALLET_ID)}, {sql_string(name)}, 'expense', "
        f"timestamptz {sql_string(f'{year:04d}-{month:02d}-01 12:00:00+00')})"
        for name, (year, month) in categories.items()
    )
    lines.append("insert into public.categories (wallet_id, name, type, created_at) values")
    lines.append("  " + cat_rows + ";")
    lines.append("")
    lines.append(f"-- 3. Insert {len(transactions)} transactions.")
    lines.append("insert into public.transactions")
    lines.append("  (wallet_id, category_id, created_by, amount_cents, description, status, occurred_at, recurrence)")
    lines.append("select")
    lines.append(f"  {sql_string(WALLET_ID)},")
    lines.append("  c.id,")
    lines.append(f"  {sql_string(USER_ID)},")
    lines.append("  t.amount_cents,")
    lines.append("  '',")
    lines.append("  'completed',")
    lines.append("  t.occurred_at,")
    lines.append("  'none'")
    lines.append("from (values")
    rows = []
    for name, cents, year, month, day in transactions:
        ts = f"{year:04d}-{month:02d}-{day:02d} 12:00:00+00"
        rows.append(f"  ({sql_string(name)}, {cents}::bigint, timestamptz {sql_string(ts)})")
    lines.append(",\n".join(rows))
    lines.append(") as t(category_name, amount_cents, occurred_at)")
    lines.append("join public.categories c")
    lines.append(f"  on c.wallet_id = {sql_string(WALLET_ID)}")
    lines.append("  and c.name = t.category_name;")
    lines.append("")
    lines.append("commit;")
    lines.append("")
    return "\n".join(lines)


def main():
    categories, transactions = collect()
    sql = emit(categories, transactions)
    OUTPUT_PATH.write_text(sql, encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH}")
    print(f"  categories:   {len(categories)}")
    print(f"  transactions: {len(transactions)}")
    print()
    print("  Categories by first-appearance month:")
    for name, (year, month) in categories.items():
        print(f"    {year:04d}-{month:02d}  {name}")
    print()
    by_year: dict[int, int] = {}
    by_year_count: dict[int, int] = {}
    for _, cents, year, _, _ in transactions:
        by_year[year] = by_year.get(year, 0) + cents
        by_year_count[year] = by_year_count.get(year, 0) + 1
    for year in sorted(by_year):
        print(f"  {year}: {by_year_count[year]:>4d} txn, {by_year[year]/100:>10,.2f}")
    grand = sum(by_year.values())
    print(f"  TOTAL: {len(transactions):>3d} txn, {grand/100:>10,.2f}")


if __name__ == "__main__":
    main()
